# markdown: redcarpet
markdown: kramdown
# kramdown:
  # auto_ids: true
  # footnote_nr: 1
  # entity_output: as_char
  # toc_levels: 1..6
  # use_coderay: false
  # parse_block_html: true
pygments: true
paginate: 5
exclude: [Gemfile, Gemfile.lock, Procfile, Rakefile, README.md, vendor, .gitignore]
keep_files: ['.git']

title: The Simple
# url: http://zhaoxuan.github.io
url: http://www.johninux.com
# url: http://localhost:4000
feed: /atom.xml
author:
  name: John
  email: zhaoxuan1727@gmail.com
  description: "Entities should not be multiplied unnecessarily."

about: "I am John."
follow:
  email: zhaoxuan1727@gmail.com
  github: https://github.com/zhaoxuan
  twitter: http://twitter.com/363602094
  google: https://plus.google.com/107483619032085919305
  facebook: http://www.facebook.com/xuan.zhao.39
description: Just an simple blog

indexContent: true

style: /css/style.css
blogDesc: Simple
favicon: /favicon.ico
theme: default

disqus: piznblog

copyright: John Zhao All rights reserved
